#!/bin/sh

# Simple script to generate CHANGELOG
# +----------------------------------+
# Author:Jocelyn GENNESSEAUX (Absolute Codes Design)


# Changelog output file
CHANGELOG_OUTPUT_FILE=CHANGELOG.md

# generate the changelog
BASEDIR=$(dirname "$0")
sh "$BASEDIR"/changelogGenerator > $CHANGELOG_OUTPUT_FILE

# prevent recursion!
# since a 'commit --amend' will trigger the post-commit script again
# we have to check if the changelog file has changed or not
res=$(git status --porcelain | grep $CHANGELOG_OUTPUT_FILE | wc -l)
if [ "$res" -gt 0 ]; then
    git add $CHANGELOG_OUTPUT_FILE
    git commit --amend
fi